### ISSUE TITLE
Fill populate

### ISSUE THREAD

**Issue by blegat** [blegat/mathraining#1]
Avec

```
rake db:populate
```

On obtient des données exemples qui sont générées par le script `lib/tasks/sample_data.rake`.
C'est juste super pratique pour remplir la base de donnée pour pouvoir tester ce qu'on implémente et ce que le design donne.
Il faudrait remplir ce fichier avec plus de données, ça augmenterait drastiquement notre efficacité !
Là j'ai mis des données un peu hardcodées mais on peut aussi en générer des aléatoires.
Pour ça, on peut s'inspirer d'[un autre que j'ai fait](https://github.com/blegat/openvoc/blob/master/lib/tasks/sample_data.rake).

**Comment by Nicolas16** [comment]
Pour info moi j'ai rajouté des trucs dans seeds.rb qui génèrent pas mal de chapitres, d'exercices, qcms, problèmes, utilisateurs, soumissions... Je me sers de ça, d'ailleurs je crois que les trucs dans sample_data.rake sont assez outdatés (ça date de quand les problèmes appartenaient à un chapitre!!)

**Comment by Nicolas16** [comment]
Improved with commit 4abb975b8ef53477e7e0292f505f89dac541fe67
