### ISSUE TITLE
Deliver mail with background jobs

### ISSUE THREAD

**Issue by Nicolas16** [blegat/mathraining#10]
Essayer de voir comment faire pour que les mails s'envoient en background.

Je ne sais plus ce que j'avais fait mais avant, soit le background job fonctionnait et les mails s'envoyaient, soit il n'était pas lancé et aucun mail n'était envoyé.

Actuellement, les mails sont envoyés mais pas en background job (poster un nouveau sujet en prévenant les élèves des deux groupes prend plus de 10 secondes car envoie 24 mails d'un coup)

Il faudrait inspecter comment faire, par exemple avec deliver_later.

**Comment by Nicolas16** [comment]
Bon j'ai réussi à ce que ça fonctionne, mais ce ne fut pas chose aisée. J'ai du installer redis parce que ça ne fonctionnait pas (bien qu'en faisant bundle install il disait qu'il avait redis, boh). Tu peux voir dans / qu'il y a un dossier redis-stable, il faudrait peut-être le mettre ailleurs (moi je me suis pas ennuyé pour l'emplacement).

Une fois que ça fonctionnait, c'était bien joli mais il fallait encore que je parvienne à lancer un background job tout en pouvant quitter la session ssh et que le background job continue à tourner. Je sais pas pourquoi, sur l'ancien serveur ça marchait comme sur des roulettes, mais ici le job s'arrêtait dès que je me barrais. J'ai tapé mon problème sur google, un mec a dit d'utiliser tmux, je me suis lancé dans l'installation de celui-ci, ce qui m'a notamment demandé d'installer libevent, bref une galère, et à la fin rien ne marche. Tu peux voir les dossier tmux-2.4 et libevent-2.1.8-stable au même endroit, tu peux en faire ce que tu veux de toutes façons rien ne marche.

Finalement je m'en suis sorti avec une alternative à tmux, à savoir screen, qui s'installait bien plus simplement. Ca m'a permis de lancer mon background job et de me barrer, et ça marche! Tu peux le voir en tapant ps -ef, le numéro 24984 c'est resque-1.27.3: Waiting for mailer.

Bref, en résumé tu peux virer tmux et libevent si tu y parviens, et tu peux mettre redis ailleurs (voir le supprimer si tu parviens à comprendre pourquoi "redis-server" ne fonctionnait pas alors que redis était mentionné lors du bundle install)

**Comment by blegat** [comment]
C'est quoi la commande que tu fais pour lancer resque ?

**Comment by Nicolas16** [comment]
`RAILS_ENV=production QUEUE=mailer rake environment resque:work &
`

(voir https://github.com/zapnap/resque_mailer )
