### ISSUE TITLE
Emoji Unicode ?

### ISSUE THREAD

**Issue by Firmaprim** [blegat/mathraining#11]
Pourquoi ne pas utiliser à la place des emojis du site (au passage, ceux de skype 😋) les emojis Unicode ?
[http://unicode.org/emoji/charts/full-emoji-list.html](url)
Du coup, plus besoin d'utiliser les images dans "mathraining/app/assets/images/".

**Comment by Nicolas16** [comment]
Ben personnellement je les trouve dégueulasses...

**Comment by Firmaprim** [comment]
Si tu le dis, mais c'est quand même plus pratique que des gifs. :)

**Comment by Nicolas16** [comment]
Ouai je sais pas, ça a toujours été comme ça j'ai pas trop envie de changer. Ca impliquerait notamment changer tous les smileys qui ont déjà été postés sur le site, ce qui me dérange assez. (Pas que ce soit compliqué à faire, mais c'est un peu comme faire croire que quelqu'un a utilisé un certain smiley alors qu'en fait il en avait utilisé un autre (celui correspondant de Skype)). Bref voilà...

**Comment by Firmaprim** [comment]
Ok, d'accord.

**Comment by Nicolas16** [comment]
Je ne comprends pas bien ce que ça a de plus pratique en fait, ça reste une image comme une autre non?

Désolé je vois que je suis un peu sec dans mes réponses, mais là j'avoue que je dois organiser la BxMO qui a lieu dans 3 jours (ainsi que d'autres choses) et donc les smileys du site me paraissent bien futiles à côté... Moi j'aime bien comme c'est pour le moment donc je préfère ne pas changer.

Sinon merci pour le bout de code concernant le rectangle gris de chargement Mathjax, je vais essayer de le rajouter pour voir si ça marche!

**Comment by Firmaprim** [comment]
Ben justement c'est pas une image. C'est un caractère. Du coup pour modifier les emojis, faut changer de police. Tu peux mettre les emojis partout (par exemple sur la barre de titre), tu peux les copier-coller, ou t'en servir comme icônes à la place d'une image (il y a pas que des têtes jaunes hein ! 😋)
Et puis, je suppose que ça fait lancer le site un peu plus rapidement (bon, c'est pas la fête non plus ...) puisqu'il a moins d'images à traiter. Mais je trouve ça quand même plus commode à gérer.

T'inquiète pas, je comprends que tu sois occupé ! 😃

J'ai vu que tu as fait les changements sur mathjax et ils marchent bien de mon côté. Finalement tu as opté pour laisser voir uniquement le message de chargement ("simple") ? Pourquoi pas, mais du coup il sert à quoi ? Enfin, quand on voit du Latex on se doute bien que c'est chargé, et puis s'il y a un problème, ça affiche une erreur directement là où il devait y avoir du Latex.

**Comment by Firmaprim** [comment]
D'accord. 
Ben pour les mises à jour, c'est pour éviter le soucis des failles. 
Bon ok, c'est pas comme si il y avait des hackers qui en veulent particulièrement à Mathraining, mais on sait jamais ...

**Comment by blegat** [comment]
@Firmaprim c'est assez dangereux d'effectuer des mises à jours lorsqu'on a 22% de test coverage. Si on avait on bon test coverage on pourait juste run les tests avec la nouvelle version et vérifier que tout fonctionne. D'ailleurs on a pour l'instant un soucis pour les tests en JS (voir #9 ). Toute aide est la bien venue pour résoudre #9 et/ou ajouter des tests :)

**Comment by Firmaprim** [comment]
En effet, c'est pas une très bonne idée. Déjà que je m'y perds dans tous les dossiers/fichiers que vous avez mis, j'imagine pas ce que ça va faire s'il y a un soucis. :')

Niveau code, j'aurai bien voulu vous aider, mais je suis vraiment nul :(. 
Le seul truc que je sais relativement bien faire, c'est tout ce qui est css ou images :p.
Sinon, je peux servir de cobaye ;)
