### ISSUE TITLE
Bundle trop vieux ?

### ISSUE THREAD

**Issue by Yacine-YA** [blegat/mathraining#25]
![image](https://user-images.githubusercontent.com/52170471/87252562-66e8ba80-c474-11ea-9ea6-e4db9e210887.png)

J'ai essayé de suivre les instructions mais je trouve rien, pour lancer MT en local 

Merci beaucoup

**Comment by Nicolas16** [comment]
Comme le message d'erreur l'indique, tu as une version de bundler trop récente. Mathraining a besoin d'une version >= 1.3.0 et < 2.0. Donc il faut que tu te renseignes sur comment installer une version moins récente de bundler sur ton ordinateur. Pour info sur Mathraining on utilise 1.16.6.
