### ISSUE TITLE
Drop 'Marquer la soumission comme correcte' link

### ISSUE THREAD

**Issue by blegat** [blegat/mathraining#3]
Maintenant qu'on peut rendre la soumission correcte par un commentaire, ne serait-ce pas une bonne idée de retirer la possibilité de la rendre correcte sans faire de commentaire ?
Ou alors on le laisse comme ça les admins ne doivent pas s'ennuyer à écrire un commentaire quand ils n'ont rien à dire.
Quoi que c'est pas tant demandé que d'écrire un petit commentaire et c'est quand même plus sympa :)

**Comment by Nicolas16** [comment]
Bon je pense qu'on peut closer ça :D
