### ISSUE TITLE
Add toggle to switch between light and dark mode

### ISSUE THREAD

**Issue by WoumBoum** [blegat/mathraining#47]
It would be useful to have a button or toggle that allows users to switch between light and dark mode for the Mathraining website. This would put the entire site into a dark theme with white text on black background.

Some details on implementation:

- Add a toggle switch or button in the header/footer
- On click, apply a "dark-mode" class to the body tag which triggers the dark theme CSS
- Store user's theme preference using localStorage or cookies
- Allow user to change back to light mode by clicking toggle again

This feature would improve comfortability and give users more choice over their experience on the site.

Let me know if any clarification is needed! I'm happy to open an issue on GitHub for this enhancement.

PS : I don't know why I can't add the enhancement label...

**Comment by Nicolas16** [comment]
Dark theme was implemented in branch bootstrap5.3, which has now been merged in master. It is now available on Mathraining.

**Comment by WoumBoum** [comment]
> Dark theme was implemented in branch bootstrap5.3, which has now been merged in master. It is now available on Mathraining.

Nice ! ;)
