### ISSUE TITLE
No code formatter

### ISSUE THREAD

**Issue by Thibault-Monnier** [blegat/mathraining#67]
Hello. I realised that there was no code formatter installed for this project. Is there a particular reason? I heard rubocop was pretty good.

**Comment by Nicolas16** [comment]
Je ne suis pas spécialement fan des code formatter, de manière générale.

Dans un gros projet, même s'il est censé y avoir un code formatter il y a toujours des développeurs qui ne l'utilisent pas. Résultat, ce sont ceux qui l'utilisent qui se retrouvent à changer le code d'autres personnes (au moment de faire tourner le code formatter sur les fichiers qu'ils ont à peine toucher).

Ici ce n'est pas un gros projet, cela fait 10 ans que je suis tout seul dessus, et je ne tiens pas à formater tout le code autrement.

**Comment by Thibault-Monnier** [comment]
Ok, pas de souci.
