### ISSUE TITLE
Fixnum deprecation

### ISSUE THREAD

**Issue by blegat** [blegat/mathraining#7]
The warnings
```
warning: constant ::Fixnum is deprecated
warning: constant ::Bignum is deprecated
```
come from the fact that we use Ruby 2.4.0 or higher. We should use Ruby on Rails 5.0.2 to fix this (we currently use 5.0.1).

**Comment by Nicolas16** [comment]
Figure-toi que j'ai fait la même recherche que tout il y a une demi-heure et que je suis arrivé à la même conclusion ! Tu veux passer à Rails 5.0.2 ?

**Comment by blegat** [comment]
Je suis pas contre, j'ai essayé mais `bundle install` n'étais pas super chaud :D

**Comment by Nicolas16** [comment]
Fixed when we used Rails v5.0.2 (see commit 984b119345d8aa1780283df115ff3d7e29409e38)
