### ISSUE TITLE
Supprimer un post soi-même.

### ISSUE THREAD

**Issue by Thibault-Monnier** [blegat/mathraining#73]
Bonjour. Je me demandais si c'était une bonne idée de rajouter une fonctionnalité permettant de supprimer ses posts sur le forum. Aujoud'hui, l'alternative est de remplacer son message par un `.`. Si la raison est de laisser une trace, il serait toujours possible d'afficher un message du style `[utilisateur] a supprimé son message`, à l'endroit où se trouvait le post avant d'être supprimé (même si ça c'est plus compliqué car il serait nécéssaire de modifier la structure de la base de données je pense).

**Comment by Nicolas16** [comment]
Je vais réfléchir à une solution, mais je n'ai pas envie que l'on puisse supprimer un message et qu'il disparaisse complètement. C'est déjà la foire pour le moment sur le Forum, donc si on permet à tout le monde d'écrire et de supprimer des trucs, ça va l'être encore plus. Normalement les gens devraient réfléchir un minimum avant d'écrire sur un Forum.

**Comment by Nicolas16** [comment]
C'est fait.
