### ISSUE TITLE
Statisques diverses non à jour

### ISSUE THREAD

**Issue by Thibault-Monnier** [blegat/mathraining#74]
Sur la page [statistiques diverses](https://www.mathraining.be/stats), certaines données ne sont pas à jour. C'est le cas de "Résolutions d'exercices" et "Soumissions aux problèmes", que je ne vois pas pourquoi retarder (ils sont actuellement au 23/09)...

**Comment by Nicolas16** [comment]
La semaine de 30/09 n'est pas encore finie, et les statistiques s'affichent uniquement pour les semaines complètes.

**Comment by Thibault-Monnier** [comment]
Merci. Sans vouloir remettre tout en question, pourquoi ne se mettent-elles pas à jour sur les statistiques de Dimanche 23:59 ? Ca permettrait d'avoir des statistiques qui ont toujours au plus une semaine de retard.

**Comment by Nicolas16** [comment]
Elles se mettent à jour tous les [lundis à 2h du matin](https://github.com/blegat/mathraining/blob/4973153d1bbe81c9c9ed70fe5373c1542beb14f9/config/schedule.rb#L27).

**Comment by Thibault-Monnier** [comment]
Ce que je veux dire, c'est que je ne comprends pas pourquoi [Records](https://github.com/blegat/mathraining/blob/4973153d1bbe81c9c9ed70fe5373c1542beb14f9/app/models/record.rb) utilise comme dernière semaine la semaine précédente.

```rb
  def self.get_monday_before_last_monday
    today = DateTime.now.in_time_zone.to_date
    yesterday = today-1
    last_sunday = yesterday - yesterday.wday
    return last_sunday-6
  end
```

Ce code renvoie la date du lundi précisément entre $-1$ semaine et $-2$ semaines.
Je pensais simplement faire
```rb
  def self.get_monday_before_last_monday
    today = DateTime.now.in_time_zone.to_date
    yesterday = today-1
    last_sunday = yesterday - yesterday.wday
    return last_sunday+1
  end
```
Avec cette deuxième version, on aurait toujours des statistiques affichés avec moins de $1$ semaine de retard.

**Comment by Nicolas16** [comment]
Oui, comme son nom l'indique, `get_monday_before_last_monday` retourne le lundi précédant lundi dernier, donc celui qui se situe entre -1 semaine et -2 semaines.

Les statistiques concernant la semaine du 30/09 ne sont affichée qu'une fois la semaine finie, c'est-à-dire à partir du 07/10 (aujourd'hui). Tu peux voir qu'elles sont affichées aujourd'hui.

Je ne comprends pas ce que tu ne comprends pas... (Je ne souhaite pas afficher de statistiques pour une semaine encore en cours, car les chiffres pour la semaine en question seraient provisoirement plus bas et ça ne serait pas clair).
