### ISSUE TITLE
Ajout de raccourcis claviers pour l'écriture

### ISSUE THREAD

**Issue by Thibault-Monnier** [blegat/mathraining#77]
Bonjour. Je pensais rajouter des raccourcis claviers pour pouvoir faciliter l'écriture de posts (et les problèmes, etc..). J'imaginais par exemple :

- Ctrl+b/g pour mettre en gras, Ctrl+u/s pour souligner, i pour l'italic, l pour les liens.
- 1, 2, 3, 4, 5, 6, 7, 8, 9 pour chacun des 9 emojis.
- Ctrl+c/h pour le texte caché.
- Ctrl+p pour activer/désactiver la prévisualisation.

Tout n'est peut-être pas essentiel, mais je pense que ça ferait un ajout sympa au moins pour gras, italic, et souligner. D'ailleurs, on pourrait même rajouter un raccourci clavier pour mettre des dollars pour le Latex.

**Comment by Nicolas16** [comment]
Honnêtement, Mathraining est un site de maths, pas un éditeur de texte. Il n'y a d'ailleurs quasi personne qui souligne ou met en gras ou en italique. L'usage commun est de juste écrire du texte avec des équations, et pour cela il suffit de taper un dollar au début et à la fin. Je ne crois pas qu'une commande ctrl+... aidera à insérer deux dollars.

Pour que des raccourcis soient utiles, il faut qu'ils soient utilisés souvent. Sinon ça prend plus de temps de se souvenir qu'il y a un raccourci et de se rappeler duquel que de cliquer sur le bouton correspondant.

À titre personnel je crois que je n'utiliserais pas de tels raccourcis même s'ils existaient. C'est mauvais signe car j'écris pourtant beaucoup sur le site. Certes je n'écris pas de soumissions, mais il n'y a pas grand monde qui formatte ses solutions avec du gras et du souligné.

**Comment by Thibault-Monnier** [comment]
C'est vrai qu'avec un peu de recul, ce n'est pas une si bonne idée...
J'ai une autre proposition. Même si ce n'est pas quelque chose qui arrive souvent, je propose de mettre les actualités nouvelles (par ex. de moins de 2 semaines) en une autre couleur, comme du jaune ; le but étant de s'assurer que les utilisateurs actifs ne ratent pas les actualités. A ce jour, si une nouvelle actualité était postée, je pense que ça me prendrai un certain temps avant de m'en rendre compte...
