### ISSUE TITLE
Testing javascript with Capybara

### ISSUE THREAD

**Issue by Nicolas16** [blegat/mathraining#9]
@blegat Est-ce que tu saurais regarder si tu sais faire fonctionner un test de javascript? J'en ai créé un, il se situe en commentaires dans subject_pages_spec.rb, mais ça ne fonctionne pas : j'ai mis `Capybara.current_driver = Capybara.javascript_driver` (j'ai trouvé ça quelque part) mais il me dit que je dois encore faire autre chose...

J'ai besoin du javascript à plusieurs endroits : le test dont je parle il en a besoin car quand on sélectionne une proposition ça fait apparaître un nouveau truc. Et j'aimerais tester les pièces jointes également, et là il y a aussi du javascript faisant apparaître des champs.

**Comment by Nicolas16** [comment]
Bon ça fait au moins trois heures que j'essaye de faire fonctionner mon test de javascripit, sans succès.

J'ai mis webkit plutôt que selenium car ça ne marchait pas.

Le problème c'est que maintenant, quand on fait des requêtes avec le javascript_server, il n'a pas accès aux trucs qu'on a défini auparavant dans la base de données, voir par exemple ce que dit ce type : 
http://stackoverflow.com/questions/7249827/cabybara-webkit-rspec-records-are-not-available
J'ai essayé plein de trucs proposés, il y a des trucs qui font fonctionner le test javascript mais alors des dizaines d'autres tests failent, bref ça me saoule :p

**Comment by blegat** [comment]
Je check ça ce soir

**Comment by blegat** [comment]
Moi j'ai
```
Capybara::ElementNotFound:
       Unable to find select box "Catégorie"
```

**Comment by Nicolas16** [comment]
Oui moi aussi mais j'ai fait du débugage et c'est parce que sign_in foire, donc il n'à pas accès à cette page. Et le sign_in foire car la base de données à 0 User. Et apparemment c'est parce que ce thread n'à pas accès à ce qui est défini ailleurs, c'est pas très clair. Si tu cherches User.count dans ce describe il vaut 2, mais si tu l'affiches sur une page du site et que tu utilises l'option debug pour le voir, on voit qu'il vaut 0

**Comment by Nicolas16** [comment]
On dirait bien que je suis parvenu à faire fonctionner des tests javascript grâce à Poltergeist :-)
